services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - API_URL=https://valorant-api.com/v1
    volumes:
      - ./shared:/app/shared:ro
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
